### PR TITLE
Laravel 6.0 support

### PR DESCRIPTION
**Pull request by oriceon**

### CODE REVIEW

**Review by markcameron — APPROVED** [review]
Thanks

**Comment by markcameron** [comment]
@oriceon Tagged a `1.0.8` version with the changes.

Let me know if you run into any issues

**Comment by oriceon** [comment]
Thanks. Is ok but now i get some error regarding an extra bracet. See new pull request please.

**Comment by markcameron** [comment]
@oriceon 
Thanks for that, tagged a `1.0.9` release. Seems that the last guy you validated a PR broke it nearly 3 years ago!

**Pull request merged**
